### ISSUE TITLE
How to solve crash

### ISSUE THREAD

**Issue by MoralFst** [skyksl066/CardConqueror#1]
I pip install six modules ready 
After selecting the window at startup, select Y to start
Python is not responding Closed

**Comment by skyksl066** [comment]
You need to send me your error code in order for me to determine the problem.

I think you may not have typed the uppercase 'Y'.
```python
asw = input('Please prepare the game first until you can see the "Start Challenge" button. Are you ready? [Y, N] default:[Y]: ')
# do main process
if asw == 'Y':
    pass
```

**Comment by MoralFst** [comment]
Thank you.I solved the problem by opening it with CMD.
