### ISSUE TITLE
repeat click card

### ISSUE THREAD

**Issue by paul061220** [skyksl066/CardConqueror#2]
When I successfully run the program, it was able to resize successfully and start flipping cards. However, after all the cards were flipped over, there was no further action. After about 3 seconds, the game automatically disconnected and started a new game, which then repeated in an infinite loop. Is this a normal situation?

**Comment by paul061220** [comment]
I have printed the 'used_idx' parameter and it always equals 0.

**Comment by skyksl066** [comment]
It's possible that the discrepancy in your environment has caused the card positions' coordinates to shift, making image recognition unsuccessful. To resolve this issue, try using the LocateCards(0.95, r'img/card.bmp') function to reposition the cards and update the coords variable with the new coordinates. Remember that the coords variable has 21 parameters, and you can enter an arbitrary value for the last parameter.

If you're still unable to obtain the coordinates accurately, consider replacing the images in the img folder.

If all else fails, you can manually input the missing coordinates. Best of luck!

```python
# replace this
coords = [(192, 85), (192, 192), (192, 299), (192, 406), 
          (299, 85), (299, 192), (299, 299), (299, 406),
          (405, 85), (405, 192), (405, 299), (405, 406),
          (512, 85), (512, 192), (512, 299), (512, 406), 
          (619, 85), (619, 192), (619, 299), (619, 406), (192, 85)]
```

```python
print(LocateCards(0.95, rf'{dir_path}/img/card.bmp'))
if __name__ == '__main__':
```

```cmd
C:\WINDOWS\system32>python D:\Python\CardConqueror\app.py
[(192, 85), (299, 85), (405, 85), (512, 85), (619, 85), (192, 192), (299, 192), (405, 192), (512, 192), (619, 192), (192, 299), (299, 299), (405, 299), (512, 299), (619, 299), (192, 406), (299, 406), (405, 406), (512, 406), (619, 406)]
```

**Comment by paul061220** [comment]
If I replace 'coords = ....' with 'coords = LocateCards(0.95, r'img/card.bmp')', the program displays 'list index out of range' error. The detailed log is as follows:

Traceback (most recent call last):
  File "C:\www\testPython\cardconqueror\app.py", line 246, in <module>
    startGame(hwnd[num])
  File "C:\www\testPython\cardconqueror\app.py", line 212, in startGame
    main()
  File "C:\www\testPython\cardconqueror\app.py", line 148, in main
    clickCard(i, True)
  File "C:\www\testPython\cardconqueror\app.py", line 110, in clickCard
    pyautogui.click(coords[card_index][0]+20, coords[card_index][1]+20, _pause=False)
IndexError: list index out of range

**Comment by paul061220** [comment]
If I replace 'coords = ....' with 'coords = LocateCards(0.95, r'img/card.bmp')', the program displays 'list index out of range' error. The detailed log is as follows:

Traceback (most recent call last):
  File "C:\www\testPython\cardconqueror\app.py", line 246, in <module>
    startGame(hwnd[num])
  File "C:\www\testPython\cardconqueror\app.py", line 212, in startGame
    main()
  File "C:\www\testPython\cardconqueror\app.py", line 148, in main
    clickCard(i, True)
  File "C:\www\testPython\cardconqueror\app.py", line 110, in clickCard
    pyautogui.click(coords[card_index][0]+20, coords[card_index][1]+20, _pause=False)
IndexError: list index out of range

**Comment by skyksl066** [comment]
鉴于你的英文能力有限，我会使用中文回答你的问题。上面的意思是，建议你调用程序打印所有卡片的坐标，而不是直接在coords后面添加LocateCards(0.95, r'img/card.bmp')。因为程序需要21个坐标，即使完美获取所有卡片的坐标，也只有20个，所以列表索引超出范围是正常的结果。

以下是修正后的建议：

1. 调用LocateCards(0.95, r'img/card.bmp')打印出所有坐标。
2. 替换并补全coords=[]内的参数，使其包含21个坐标。
3. 如果无法完整获取20个坐标，请自行查看并补全缺失的坐标，坐标之间应连贯。

**Comment by skyksl066** [comment]
鑒於你的英文能力有限，我會使用中文回答你的問題。上面的意思是，建議你調用程式列印所有卡片的座標，而不是直接在coords後面添加LocateCards(0.95, r'img/card.bmp')。因為程式需要21個座標，即使完美獲取所有卡片的座標，也只有20個，所以列表索引超出範圍是正常的結果。

以下是修改後的建議：

1. 調用LocateCards(0.95, r'img/card.bmp')列印所有座標。
2. 替換並補全coords=[]內的參數，使其包含21個座標。
3. 如果無法完整獲取20個座標，請自行查看並補全缺失的座標，座標之間應連貫。

**Comment by paul061220** [comment]
OK 理解並且試成功了 
原本附的 card.bmp 黨似乎識別不出來
LocateCards(0.95, r'img/card.bmp') 出來後的結果是 空的
我重新截了一張圖替換後就有得到座標了
感謝您的回答
